version: 2

multi-ecosystem-groups:
  weekly-dependency-refresh:
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps)
      include: scope

updates:
  - package-ecosystem: npm
    directory: /web/frontend
    multi-ecosystem-group: weekly-dependency-refresh
    patterns:
      - '*'

  - package-ecosystem: pip
    directory: /web/backend
    multi-ecosystem-group: weekly-dependency-refresh
    patterns:
      - '*'

  - package-ecosystem: docker
    directory: /
    multi-ecosystem-group: weekly-dependency-refresh
    patterns:
      - '*'

  - package-ecosystem: github-actions
    directory: /
    multi-ecosystem-group: weekly-dependency-refresh
    patterns:
      - '*'
